# Generated by Django 5.0.4 on 2024-05-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Electronics'), (2, 'Books'), (3, 'Clothing'), (4, 'Sports'), (5, 'Other')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ManyToManyField(related_name='categories', to='store.product', verbose_name='Product'),
        ),
    ]
