# Generated by Django 5.0.4 on 2024-05-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Electronics'), (2, 'Books'), (3, 'Clothing'), (4, 'Sports'), (5, 'Other')], default=5, verbose_name='Category'),
        ),
    ]
