# Generated by Django 5.0.4 on 2024-05-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='categories', to='store.product', verbose_name='Product'),
        ),
    ]
